### ISSUE TITLE
SFC log uploads should be a proper API endpoint

### ISSUE THREAD

**Issue by Dhwty** [f-list/fserv#17]
Why is this not part of the API? Apparently uploading logs currently requires initiating a web session on behalf of the user, which kind of means the client has to have stored the user’s password or to request it again in order to upload logs. (Admittedly, some clients do already have a tickbox for this, but still…)

Hexxy sez: as for the API, I was gonna use oAuth2 for it somehow as I've messed around with that quite a bit by now.

**Comment by zwagoth** [comment]
It happened, and there are actually docs for it. Wooooo.
