### ISSUE TITLE
Accepting a chat report doesn't log who accepted it anywhere (semi-)permanent

### ISSUE THREAD

**Issue by Dhwty** [f-list/fserv#33]
Natsudra: Ugh, there's no way to log who accepts them, is there?
Natsudra: That'd be brilliant to have.
Aniko: Ultimately it would probably be a good idea to log who accepted a log, yeah.  But currently the chat doesn't send that information back to the site or store it anywhere.

Just a note, because this seems kinda useful.

**Comment by zwagoth** [comment]
Woo, fixed.
